"""API routes for SepsisSentinel REST endpoints."""
import logging

from fastapi import APIRouter, HTTPException, Path, status

from app.core.config import settings
from app.models.schemas import (
    AnalyzeRequest,
    AnalyzeResponse,
    CustomAnalysisRequest,
    HealthResponse,
    PatientDetailResponse,
    PatientListResponse,
)
from app.services.sepsis_service import SepsisService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["sepsis"])

# Lazy service initialisation to avoid import-time side effects
_sepsis_service = None


def get_sepsis_service() -> SepsisService:
    """Return the singleton SepsisService, creating it on first call."""
    global _sepsis_service
    if _sepsis_service is None:
        _sepsis_service = SepsisService()
    return _sepsis_service


def _raise_http_error(exc: Exception) -> None:
    """Translate domain errors into HTTP exceptions."""
    if isinstance(exc, ValueError):
        logger.error("Validation error: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    if isinstance(exc, FileNotFoundError):
        logger.error("File not found: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(exc),
        ) from exc

    logger.error("Unexpected error during request handling: %s", exc)
    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail=f"Internal server error: {exc}",
    ) from exc


@router.get(
    "/patients",
    response_model=PatientListResponse,
    status_code=status.HTTP_200_OK,
    summary="List available sample patients",
)
async def list_patients() -> PatientListResponse:
    """Return summary info for all sample patients.

    Returns:
        PatientListResponse with a list of patients.
    """
    service = get_sepsis_service()
    patients = service.list_patients()
    return PatientListResponse(patients=patients)


@router.get(
    "/patients/{patient_id}",
    response_model=PatientDetailResponse,
    status_code=status.HTTP_200_OK,
    summary="Get a sample patient",
    description="Returns the full JSON payload for a built-in sample patient.",
)
async def get_patient(
    patient_id: int = Path(..., ge=1, le=3, description="Sample patient ID"),
) -> PatientDetailResponse:
    """Return a single sample patient resource."""
    try:
        service = get_sepsis_service()
        result = service.get_patient(patient_id)
        return PatientDetailResponse(
            patient_id=result["patient_id"],
            patient_data=result["patient_data"],
        )
    except Exception as exc:
        _raise_http_error(exc)


@router.post(
    "/patients/{patient_id}/analyses",
    response_model=AnalyzeResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create an analysis for a sample patient",
    description=(
        "Runs the sepsis model for a built-in sample patient and returns the "
        "generated risk assessment."
    ),
)
async def create_sample_patient_analysis(
    patient_id: int = Path(..., ge=1, le=3, description="Sample patient ID"),
) -> AnalyzeResponse:
    """Create an analysis resource for a sample patient."""
    try:
        service = get_sepsis_service()
        result = service.analyze_sample_patient(patient_id)
        return AnalyzeResponse(
            patient_id=result["patient_id"],
            analysis=result["analysis"],
            output_file=result["output_file"],
            source=result["source"],
        )
    except Exception as exc:
        _raise_http_error(exc)


@router.post(
    "/analyses",
    response_model=AnalyzeResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create an analysis for custom patient data",
    description=(
        "Accepts raw patient data and returns a sepsis risk assessment "
        "generated by the AI pipeline."
    ),
)
async def create_custom_analysis(
    request: CustomAnalysisRequest,
) -> AnalyzeResponse:
    """Create an analysis resource from custom patient data."""
    try:
        service = get_sepsis_service()
        result = service.analyze_custom_patient(request.patient_data)
        return AnalyzeResponse(
            patient_id=result["patient_id"],
            analysis=result["analysis"],
            output_file=result["output_file"],
            source=result["source"],
        )
    except Exception as exc:
        _raise_http_error(exc)


@router.post(
    "/analyze",
    response_model=AnalyzeResponse,
    status_code=status.HTTP_200_OK,
    deprecated=True,
    summary="Legacy analysis endpoint",
    description=(
        "Backward-compatible endpoint. Prefer POST /patients/{patient_id}/"
        "analyses for sample patients or POST /analyses for custom payloads."
    ),
)
async def analyze(request: AnalyzeRequest) -> AnalyzeResponse:
    """Backward-compatible analysis endpoint."""
    try:
        service = get_sepsis_service()
        if request.patient_id is None and request.patient_data is None:
            raise ValueError("Provide either patient_id (1-3) or patient_data.")
        if request.patient_id is not None and request.patient_data is not None:
            raise ValueError(
                "Provide only one of patient_id or patient_data, not both."
            )
        if request.patient_id is not None:
            result = service.analyze_sample_patient(request.patient_id)
        else:
            result = service.analyze_custom_patient(request.patient_data)

        return AnalyzeResponse(
            patient_id=result["patient_id"],
            analysis=result["analysis"],
            output_file=result["output_file"],
            source=result["source"],
        )
    except Exception as exc:
        _raise_http_error(exc)


@router.get(
    "/health",
    response_model=HealthResponse,
    status_code=status.HTTP_200_OK,
    summary="Health check endpoint",
)
async def health_check() -> HealthResponse:
    """Return service health status and configuration info.

    Returns:
        HealthResponse with status, version, and OpenAI configuration.
    """
    openai_configured = bool(settings.openai_api_key)

    api_accessible = False
    if openai_configured:
        api_key = settings.openai_api_key
        api_accessible = api_key.startswith("sk-") and len(api_key) > 20

    return HealthResponse(
        status="healthy" if (openai_configured and api_accessible) else "degraded",
        version=settings.api_version,
        model=settings.openai_model if openai_configured else None,
        openai_configured=openai_configured,
    )
