"""Tests for the handover orchestrator — chart assembly is attached to results."""

from unittest.mock import AsyncMock, patch

import pytest

from app.models.schemas import GenerateSummaryRequest
from app.services.nurse_handover_service import generate_shift_summaries


@pytest.mark.asyncio
async def test_shift_summaries_share_generated_at_and_current_status(
    critical_patient,
    valid_gpt_response_critical,
):
    request = GenerateSummaryRequest(
        handover_nurse="Sarah Mitchell",
        patient=critical_patient,
    )

    with patch(
        "app.services.nurse_handover_service.call_gpt",
        new=AsyncMock(return_value=valid_gpt_response_critical),
    ):
        response = await generate_shift_summaries(request)

    assert response.generated_at is not None
    assert response.generated_at.tzinfo is not None
    assert response.generated_by_ai_for == "Sarah Mitchell"
    assert "**Situation**" in response.formatted_text
    assert "**Diagnosis**" in response.formatted_text
    assert "**Generated by AI for:** Sarah Mitchell" in response.formatted_text
    assert "Penicillin" in response.formatted_text
    assert "Fall risk" in response.formatted_text
    assert "Repeat chest X-ray" in response.formatted_text
    assert set(response.model_dump().keys()) == {
        "formatted_text",
        "generated_by_ai_for",
        "generated_at",
    }
